#!/usr/bin/env python3
"""
Aliyun Spec-Driven Development - Code Generator
根据解析后的API规范生成客户端代码
"""

import json
import argparse
import sys
from pathlib import Path
from typing import Dict, Any, List


class CodeGenerator:
    """代码生成器"""
    
    def __init__(self, spec_data: Dict[str, Any]):
        self.spec_data = spec_data
        self.info = spec_data.get('info', {})
        self.base_url = spec_data.get('baseUrl', '')
        self.endpoints = spec_data.get('endpoints', [])
        self.models = spec_data.get('models', [])
    
    def generate_typescript(self, output_dir: str):
        """生成TypeScript客户端代码"""
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        
        # 生成类型定义
        self._generate_ts_types(output_path)
        
        # 生成客户端类
        self._generate_ts_client(output_path)
        
        # 生成index.ts
        self._generate_ts_index(output_path)
        
        print(f"TypeScript client generated in: {output_dir}")
    
    def _generate_ts_types(self, output_path: Path):
        """生成TypeScript类型定义"""
        content = f"""/**
 * {self.info.get('title', 'API')} - TypeScript Type Definitions
 * Auto-generated by Aliyun Spec-Driven Development
 */

// Base types
export interface ApiResponse<T> {{
  data: T;
  status: number;
  message?: string;
}}

export interface ApiError {{
  code: string;
  message: string;
  details?: any;
}}

"""
        
        # 生成模型类型
        for model in self.models:
            content += f"export interface {model['name']} {{\n"
            for prop in model.get('properties', []):
                ts_type = self._get_ts_type(prop['type'], prop.get('format', ''))
                optional = '?' if prop['name'] not in model.get('required', []) else ''
                content += f"  {prop['name']}{optional}: {ts_type};\n"
            content += "}\n\n"
        
        with open(output_path / 'types.ts', 'w', encoding='utf-8') as f:
            f.write(content)
    
    def _generate_ts_client(self, output_path: Path):
        """生成TypeScript客户端类"""
        class_name = self.info.get('title', 'Api').replace(' ', '') + 'Client'
        
        content = f"""/**
 * {self.info.get('title', 'API')} - TypeScript Client
 * Auto-generated by Aliyun Spec-Driven Development
 */

import {{ ApiResponse, ApiError }} from './types';

export interface ClientConfig {{
  baseUrl: string;
  apiKey?: string;
  timeout?: number;
  headers?: Record<string, string>;
}}

export class {class_name} {{
  private baseUrl: string;
  private apiKey?: string;
  private timeout: number;
  private headers: Record<string, string>;

  constructor(config: ClientConfig) {{
    this.baseUrl = config.baseUrl || '{self.base_url}';
    this.apiKey = config.apiKey;
    this.timeout = config.timeout || 30000;
    this.headers = config.headers || {{}};
  }}

  private async request<T>(
    method: string,
    path: string,
    data?: any,
    params?: Record<string, string>
  ): Promise<ApiResponse<T>> {{
    const url = new URL(path, this.baseUrl);
    
    if (params) {{
      Object.entries(params).forEach(([key, value]) => {{
        url.searchParams.append(key, value);
      }});
    }}

    const headers: Record<string, string> = {{
      'Content-Type': 'application/json',
      ...this.headers,
    }};

    if (this.apiKey) {{
      headers['Authorization'] = `Bearer ${{this.apiKey}}`;
    }}

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), this.timeout);

    try {{
      const response = await fetch(url.toString(), {{
        method,
        headers,
        body: data ? JSON.stringify(data) : undefined,
        signal: controller.signal,
      }});

      clearTimeout(timeoutId);

      if (!response.ok) {{
        const error: ApiError = await response.json();
        throw new Error(error.message || `HTTP error! status: ${{response.status}}`);
      }}

      const result = await response.json();
      return {{
        data: result,
        status: response.status,
      }};
    }} catch (error) {{
      clearTimeout(timeoutId);
      throw error;
    }}
  }}

"""
        
        # 生成API方法
        for endpoint in self.endpoints:
            method_name = self._get_method_name(endpoint)
            params = self._get_method_params(endpoint)
            return_type = self._get_return_type(endpoint)
            
            content += f"  async {method_name}({params}): Promise<ApiResponse<{return_type}>> {{\n"
            content += f"    return this.request<{return_type}>(\n"
            content += f"      '{endpoint['method']}',\n"
            content += f"      '{endpoint['path']}',\n"
            
            if endpoint['method'] in ['POST', 'PUT', 'PATCH']:
                content += f"      data,\n"
            else:
                content += f"      undefined,\n"
            
            if endpoint.get('parameters'):
                content += f"      params\n"
            else:
                content += f"      undefined\n"
            
            content += f"    );\n"
            content += f"  }}\n\n"
        
        content += "}\n"
        
        with open(output_path / 'client.ts', 'w', encoding='utf-8') as f:
            f.write(content)
    
    def _generate_ts_index(self, output_path: Path):
        """生成TypeScript index.ts"""
        class_name = self.info.get('title', 'Api').replace(' ', '') + 'Client'
        
        content = f"""/**
 * {self.info.get('title', 'API')} - Main Entry Point
 * Auto-generated by Aliyun Spec-Driven Development
 */

export * from './types';
export {{ {class_name} }} from './client';
"""
        
        with open(output_path / 'index.ts', 'w', encoding='utf-8') as f:
            f.write(content)
    
    def _get_ts_type(self, type_name: str, format: str = '') -> str:
        """获取TypeScript类型"""
        type_mapping = {
            'string': 'string',
            'integer': 'number',
            'number': 'number',
            'boolean': 'boolean',
            'array': 'any[]',
            'object': 'Record<string, any>',
        }
        
        if format == 'date-time':
            return 'string'
        
        return type_mapping.get(type_name, 'any')
    
    def _get_method_name(self, endpoint: Dict) -> str:
        """获取方法名"""
        if endpoint.get('operationId'):
            return endpoint['operationId']
        
        # 从路径生成方法名
        path = endpoint['path'].replace('/', '_').replace('{', '').replace('}', '')
        method = endpoint['method'].lower()
        return f"{method}{path}"
    
    def _get_method_params(self, endpoint: Dict) -> str:
        """获取方法参数"""
        params = []
        
        # 路径参数
        for param in endpoint.get('parameters', []):
            if param['in'] == 'path':
                params.append(f"{param['name']}: string")
        
        # 查询参数
        query_params = [p for p in endpoint.get('parameters', []) if p['in'] == 'query']
        if query_params:
            params.append("params?: Record<string, string>")
        
        # 请求体
        if endpoint['method'] in ['POST', 'PUT', 'PATCH']:
            params.append("data?: any")
        
        return ', '.join(params)
    
    def _get_return_type(self, endpoint: Dict) -> str:
        """获取返回类型"""
        responses = endpoint.get('responses', {})
        success_response = responses.get('200', {})
        schema = success_response.get('schema', {})
        
        if schema.get('type') == 'array':
            return 'any[]'
        
        return 'any'
    
    def generate_python(self, output_dir: str):
        """生成Python客户端代码"""
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        
        # 生成models.py
        self._generate_py_models(output_path)
        
        # 生成client.py
        self._generate_py_client(output_path)
        
        # 生成__init__.py
        self._generate_py_init(output_path)
        
        print(f"Python client generated in: {output_dir}")
    
    def _generate_py_models(self, output_path: Path):
        """生成Python数据模型"""
        content = f"""\"\"\"
{self.info.get('title', 'API')} - Python Data Models
Auto-generated by Aliyun Spec-Driven Development
\"\"\"

from dataclasses import dataclass
from typing import Optional, List, Dict, Any
from datetime import datetime


"""
        
        for model in self.models:
            content += f"@dataclass\nclass {model['name']}:\n"
            content += f'    """{model.get("description", model["name"])}"""\n\n'
            
            for prop in model.get('properties', []):
                py_type = self._get_py_type(prop['type'], prop.get('format', ''))
                default = 'None' if prop['name'] not in model.get('required', []) else ''
                if default:
                    content += f"    {prop['name']}: Optional[{py_type}] = {default}\n"
                else:
                    content += f"    {prop['name']}: {py_type}\n"
            
            content += "\n"
        
        with open(output_path / 'models.py', 'w', encoding='utf-8') as f:
            f.write(content)
    
    def _generate_py_client(self, output_path: Path):
        """生成Python客户端类"""
        class_name = self.info.get('title', 'Api').replace(' ', '') + 'Client'
        
        content = f"""\"\"\"
{self.info.get('title', 'API')} - Python Client
Auto-generated by Aliyun Spec-Driven Development
\"\"\"

import requests
from typing import Optional, Dict, Any, List
from .models import *


class {class_name}:
    \"\"\"Client for {self.info.get('title', 'API')}\"\"\"
    
    def __init__(
        self,
        base_url: str = '{self.base_url}',
        api_key: Optional[str] = None,
        timeout: int = 30
    ):
        self.base_url = base_url.rstrip('/')
        self.api_key = api_key
        self.timeout = timeout
        self.session = requests.Session()
        
        if api_key:
            self.session.headers['Authorization'] = f'Bearer {{api_key}}'
    
    def _request(
        self,
        method: str,
        path: str,
        data: Optional[Dict] = None,
        params: Optional[Dict] = None
    ) -> Dict[str, Any]:
        \"\"\"Make HTTP request\"\"\"
        url = f'{{self.base_url}}{{path}}'
        
        response = self.session.request(
            method=method,
            url=url,
            json=data,
            params=params,
            timeout=self.timeout
        )
        
        response.raise_for_status()
        return response.json()

"""
        
        # 生成API方法
        for endpoint in self.endpoints:
            method_name = self._get_method_name(endpoint)
            params = self._get_py_method_params(endpoint)
            return_type = self._get_py_return_type(endpoint)
            
            content += f"    def {method_name}(self, {params}) -> Dict[str, Any]:\n"
            content += f'        \"\"\"{endpoint.get("summary", endpoint["path"])}\"\"\"\n'
            
            if endpoint['method'] in ['POST', 'PUT', 'PATCH']:
                content += f"        return self._request('{endpoint['method']}', '{endpoint['path']}', data=data)\n"
            else:
                content += f"        return self._request('{endpoint['method']}', '{endpoint['path']}', params=params)\n"
            
            content += "\n"
        
        with open(output_path / 'client.py', 'w', encoding='utf-8') as f:
            f.write(content)
    
    def _generate_py_init(self, output_path: Path):
        """生成Python __init__.py"""
        class_name = self.info.get('title', 'Api').replace(' ', '') + 'Client'
        
        content = f"""\"\"\"
{self.info.get('title', 'API')} - Python Package
Auto-generated by Aliyun Spec-Driven Development
\"\"\"

from .models import *
from .client import {class_name}

__all__ = ['{class_name}']
"""
        
        with open(output_path / '__init__.py', 'w', encoding='utf-8') as f:
            f.write(content)
    
    def _get_py_type(self, type_name: str, format: str = '') -> str:
        """获取Python类型"""
        type_mapping = {
            'string': 'str',
            'integer': 'int',
            'number': 'float',
            'boolean': 'bool',
            'array': 'List[Any]',
            'object': 'Dict[str, Any]',
        }
        
        if format == 'date-time':
            return 'datetime'
        
        return type_mapping.get(type_name, 'Any')
    
    def _get_py_method_params(self, endpoint: Dict) -> str:
        """获取Python方法参数"""
        params = ['self']
        
        # 路径参数
        for param in endpoint.get('parameters', []):
            if param['in'] == 'path':
                params.append(f"{param['name']}: str")
        
        # 查询参数
        query_params = [p for p in endpoint.get('parameters', []) if p['in'] == 'query']
        if query_params:
            params.append("params: Optional[Dict[str, str]] = None")
        
        # 请求体
        if endpoint['method'] in ['POST', 'PUT', 'PATCH']:
            params.append("data: Optional[Dict[str, Any]] = None")
        
        return ', '.join(params)
    
    def _get_py_return_type(self, endpoint: Dict) -> str:
        """获取Python返回类型"""
        return 'Dict[str, Any]'


def main():
    parser = argparse.ArgumentParser(description='Generate client code from parsed spec')
    parser.add_argument('--spec', '-s', required=True, help='Parsed spec file path')
    parser.add_argument('--language', '-l', required=True, choices=['typescript', 'python'], help='Target language')
    parser.add_argument('--output', '-o', required=True, help='Output directory')
    
    args = parser.parse_args()
    
    try:
        with open(args.spec, 'r', encoding='utf-8') as f:
            spec_data = json.load(f)
        
        generator = CodeGenerator(spec_data)
        
        if args.language == 'typescript':
            generator.generate_typescript(args.output)
        elif args.language == 'python':
            generator.generate_python(args.output)
        
        print(f"Code generation completed successfully!")
        
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
